
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8076:80"
    depends_on:
      - app
    container_name: project_nginx

  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www/
    depends_on:
        - db
    container_name: project_app

  db:
      image: postgres:latest
      restart: always
      volumes:
              - ./tmp/db3:/var/lib/postgresql/data
      environment:
              POSTGRES_DB: laravel
              POSTGRES_USER: postgres
              POSTGRES_PASSWORD: postgres
      ports:
              - 8101:5432
      container_name: project_db



  pgadmin4:
      container_name: pgadmin4
      image: dpage/pgadmin4
      restart: always
      environment:
          PGADMIN_DEFAULT_EMAIL: abazov1477@gmail.com
          PGADMIN_DEFAULT_PASSWORD: root
      ports:
          - "5050:80"
      volumes:
          - pgadmin-data:/var/lib/pgadmin
volumes:
      local_pgdata:
      pgadmin-data:




